"""
Shared mock data for all fake backend APIs.

Orders:  ORD-1001 .. ORD-1020
Products: 40 entries used by inventory_api.
"""

from __future__ import annotations

# ---------------------------------------------------------------------------
# Orders — 20 entries with varied states
# ---------------------------------------------------------------------------
# Fields used by different APIs:
#   orders_api   : status, status_detail, estimated_delivery, tracking_url
#   cancel_check : can_cancel, cancel_escalation_trigger
#   refunds_api  : refund_status, refund_amount, refund_eta, refund_detail

ORDERS: dict[str, dict] = {
    "ORD-1001": {
        "order_id": "ORD-1001",
        "customer_name": "Ana Costa",
        "status": "processing",
        "status_detail": "Your order is being prepared at our warehouse.",
        "estimated_delivery": "2026-05-08",
        "tracking_url": "https://track.olamarket.pt/ORD-1001",
        "can_cancel": True,
        "cancel_escalation_trigger": None,
        "refund_status": None,
        "refund_amount": None,
        "refund_eta": None,
        "refund_detail": "No refund has been requested for this order.",
        "total_amount": 45.99,
    },
    "ORD-1002": {
        "order_id": "ORD-1002",
        "customer_name": "Bruno Silva",
        "status": "shipped",
        "status_detail": "Your order has left our warehouse and is on its way.",
        "estimated_delivery": "2026-05-05",
        "tracking_url": "https://track.olamarket.pt/ORD-1002",
        "can_cancel": False,
        "cancel_escalation_trigger": "order_already_shipped",
        "refund_status": None,
        "refund_amount": None,
        "refund_eta": None,
        "refund_detail": "No refund has been requested for this order.",
        "total_amount": 89.50,
    },
    "ORD-1003": {
        "order_id": "ORD-1003",
        "customer_name": "Catarina Mendes",
        "status": "delivered",
        "status_detail": "Delivered on 2026-04-29. Signed by recipient.",
        "estimated_delivery": "2026-04-29",
        "tracking_url": "https://track.olamarket.pt/ORD-1003",
        "can_cancel": False,
        "cancel_escalation_trigger": "order_fulfilled",
        "refund_status": "pending",
        "refund_amount": "€32.00",
        "refund_eta": "2026-05-06",
        "refund_detail": "Return received. Refund will be processed within 5-7 business days.",
        "total_amount": 32.00,
    },
    "ORD-1004": {
        "order_id": "ORD-1004",
        "customer_name": "Diogo Ferreira",
        "status": "lost",
        "status_detail": "Carrier reports the package as lost. We sincerely apologise.",
        "estimated_delivery": "N/A",
        "tracking_url": "https://track.olamarket.pt/ORD-1004",
        "can_cancel": False,
        "cancel_escalation_trigger": "order_already_shipped",
        "refund_status": "approved",
        "refund_amount": "€120.00",
        "refund_eta": "2026-05-07",
        "refund_detail": "Full refund approved due to lost package. Credit will appear in 3-5 business days.",
        "total_amount": 120.00,
    },
    "ORD-1005": {
        "order_id": "ORD-1005",
        "customer_name": "Elisa Rodrigues",
        "status": "processing",
        "status_detail": "Payment confirmed. Your order enters fulfilment today.",
        "estimated_delivery": "2026-05-09",
        "tracking_url": "https://track.olamarket.pt/ORD-1005",
        "can_cancel": True,
        "cancel_escalation_trigger": None,
        "refund_status": None,
        "refund_amount": None,
        "refund_eta": None,
        "refund_detail": "No refund has been requested for this order.",
        "total_amount": 67.80,
    },
    "ORD-1006": {
        "order_id": "ORD-1006",
        "customer_name": "Filipe Nunes",
        "status": "delivered",
        "status_detail": "Delivered on 2026-04-20.",
        "estimated_delivery": "2026-04-20",
        "tracking_url": "https://track.olamarket.pt/ORD-1006",
        "can_cancel": False,
        "cancel_escalation_trigger": "order_fulfilled",
        "refund_status": "pending",
        "refund_amount": "€55.00",
        "refund_eta": "2026-05-10",
        "refund_detail": "Return label issued 2026-04-28. Awaiting item at warehouse.",
        "total_amount": 55.00,
    },
    "ORD-1007": {
        "order_id": "ORD-1007",
        "customer_name": "Gabriela Lopes",
        "status": "delivered",
        "status_detail": "Delivered on 2026-04-10.",
        "estimated_delivery": "2026-04-10",
        "tracking_url": "https://track.olamarket.pt/ORD-1007",
        "can_cancel": False,
        "cancel_escalation_trigger": "order_fulfilled",
        "refund_status": "completed",
        "refund_amount": "€78.50",
        "refund_eta": "2026-04-17",
        "refund_detail": "Refund completed on 2026-04-17. Amount returned to original payment method.",
        "total_amount": 78.50,
    },
    "ORD-1008": {
        "order_id": "ORD-1008",
        "customer_name": "Hélder Carvalho",
        "status": "payment_failed",
        "status_detail": "Payment could not be processed. Please update your payment method.",
        "estimated_delivery": "N/A",
        "tracking_url": "https://track.olamarket.pt/ORD-1008",
        "can_cancel": True,
        "cancel_escalation_trigger": None,
        "refund_status": None,
        "refund_amount": None,
        "refund_eta": None,
        "refund_detail": "No payment was taken — no refund needed.",
        "total_amount": 0.00,
    },
    "ORD-1009": {
        "order_id": "ORD-1009",
        "customer_name": "Inês Martins",
        "status": "delivered",
        "status_detail": "Delivered on 2026-04-25.",
        "estimated_delivery": "2026-04-25",
        "tracking_url": "https://track.olamarket.pt/ORD-1009",
        "can_cancel": False,
        "cancel_escalation_trigger": "order_fulfilled",
        "refund_status": None,
        "refund_amount": None,
        "refund_eta": None,
        "refund_detail": "No refund has been requested for this order.",
        "total_amount": 29.99,
    },
    "ORD-1010": {
        "order_id": "ORD-1010",
        "customer_name": "João Pereira",
        "status": "shipped",
        "status_detail": "Out for delivery. Expect arrival today.",
        "estimated_delivery": "2026-05-04",
        "tracking_url": "https://track.olamarket.pt/ORD-1010",
        "can_cancel": False,
        "cancel_escalation_trigger": "order_already_shipped",
        "refund_status": None,
        "refund_amount": None,
        "refund_eta": None,
        "refund_detail": "No refund has been requested for this order.",
        "total_amount": 149.00,
    },
    "ORD-1011": {
        "order_id": "ORD-1011",
        "customer_name": "Karen Santos",
        "status": "processing",
        "status_detail": "Order confirmed and in the queue.",
        "estimated_delivery": "2026-05-10",
        "tracking_url": "https://track.olamarket.pt/ORD-1011",
        "can_cancel": True,
        "cancel_escalation_trigger": None,
        "refund_status": None,
        "refund_amount": None,
        "refund_eta": None,
        "refund_detail": "No refund has been requested for this order.",
        "total_amount": 34.00,
    },
    "ORD-1012": {
        "order_id": "ORD-1012",
        "customer_name": "Luísa Faria",
        "status": "cancelled",
        "status_detail": "Order cancelled at customer request on 2026-04-30.",
        "estimated_delivery": "N/A",
        "tracking_url": "https://track.olamarket.pt/ORD-1012",
        "can_cancel": False,
        "cancel_escalation_trigger": "order_already_shipped",
        "refund_status": "completed",
        "refund_amount": "€22.50",
        "refund_eta": "2026-05-02",
        "refund_detail": "Refund processed on 2026-05-02.",
        "total_amount": 22.50,
    },
    "ORD-1013": {
        "order_id": "ORD-1013",
        "customer_name": "Miguel Teixeira",
        "status": "delivered",
        "status_detail": "Delivered on 2026-04-22.",
        "estimated_delivery": "2026-04-22",
        "tracking_url": "https://track.olamarket.pt/ORD-1013",
        "can_cancel": False,
        "cancel_escalation_trigger": "order_fulfilled",
        "refund_status": None,
        "refund_amount": None,
        "refund_eta": None,
        "refund_detail": "No refund has been requested for this order.",
        "total_amount": 59.99,
    },
    "ORD-1014": {
        "order_id": "ORD-1014",
        "customer_name": "Natalia Gomes",
        "status": "shipped",
        "status_detail": "In transit. Currently at Porto sorting facility.",
        "estimated_delivery": "2026-05-06",
        "tracking_url": "https://track.olamarket.pt/ORD-1014",
        "can_cancel": False,
        "cancel_escalation_trigger": "order_already_shipped",
        "refund_status": None,
        "refund_amount": None,
        "refund_eta": None,
        "refund_detail": "No refund has been requested for this order.",
        "total_amount": 200.00,
    },
    "ORD-1015": {
        "order_id": "ORD-1015",
        "customer_name": "Osvaldo Pinto",
        "status": "processing",
        "status_detail": "Awaiting stock from supplier. Ships within 2 days.",
        "estimated_delivery": "2026-05-11",
        "tracking_url": "https://track.olamarket.pt/ORD-1015",
        "can_cancel": True,
        "cancel_escalation_trigger": None,
        "refund_status": None,
        "refund_amount": None,
        "refund_eta": None,
        "refund_detail": "No refund has been requested for this order.",
        "total_amount": 15.00,
    },
    "ORD-1016": {
        "order_id": "ORD-1016",
        "customer_name": "Patricia Alves",
        "status": "delivered",
        "status_detail": "Delivered on 2026-04-18.",
        "estimated_delivery": "2026-04-18",
        "tracking_url": "https://track.olamarket.pt/ORD-1016",
        "can_cancel": False,
        "cancel_escalation_trigger": "order_fulfilled",
        "refund_status": None,
        "refund_amount": None,
        "refund_eta": None,
        "refund_detail": "No refund has been requested for this order.",
        "total_amount": 88.00,
    },
    "ORD-1017": {
        "order_id": "ORD-1017",
        "customer_name": "Quim Barbosa",
        "status": "delivered",
        "status_detail": "Delivered on 2026-04-15.",
        "estimated_delivery": "2026-04-15",
        "tracking_url": "https://track.olamarket.pt/ORD-1017",
        "can_cancel": False,
        "cancel_escalation_trigger": "order_fulfilled",
        "refund_status": "pending",
        "refund_amount": "€44.00",
        "refund_eta": "2026-05-09",
        "refund_detail": "Return received at warehouse 2026-05-02. Processing within 5 days.",
        "total_amount": 44.00,
    },
    "ORD-1018": {
        "order_id": "ORD-1018",
        "customer_name": "Rita Cunha",
        "status": "shipped",
        "status_detail": "Shipped via CTT Express. On the way.",
        "estimated_delivery": "2026-05-07",
        "tracking_url": "https://track.olamarket.pt/ORD-1018",
        "can_cancel": False,
        "cancel_escalation_trigger": "order_already_shipped",
        "refund_status": None,
        "refund_amount": None,
        "refund_eta": None,
        "refund_detail": "No refund has been requested for this order.",
        "total_amount": 73.00,
    },
    "ORD-1019": {
        "order_id": "ORD-1019",
        "customer_name": "Sandro Melo",
        "status": "processing",
        "status_detail": "Order confirmed. Expected to ship tomorrow.",
        "estimated_delivery": "2026-05-09",
        "tracking_url": "https://track.olamarket.pt/ORD-1019",
        "can_cancel": True,
        "cancel_escalation_trigger": None,
        "refund_status": None,
        "refund_amount": None,
        "refund_eta": None,
        "refund_detail": "No refund has been requested for this order.",
        "total_amount": 99.00,
    },
    "ORD-1020": {
        "order_id": "ORD-1020",
        "customer_name": "Teresa Vieira",
        "status": "delivered",
        "status_detail": "Delivered on 2026-04-30. Left at door.",
        "estimated_delivery": "2026-04-30",
        "tracking_url": "https://track.olamarket.pt/ORD-1020",
        "can_cancel": False,
        "cancel_escalation_trigger": "order_fulfilled",
        "refund_status": None,
        "refund_amount": None,
        "refund_eta": None,
        "refund_detail": "No refund has been requested for this order.",
        "total_amount": 62.00,
    },
}


# ---------------------------------------------------------------------------
# Products — 40 entries used by inventory_api
# ---------------------------------------------------------------------------

PRODUCTS: list[dict] = [
    # Home & Living (10)
    {"name": "golden mirror", "in_stock": True, "stock_count": 8, "restock_message": ""},
    {"name": "linen throw blanket", "in_stock": True, "stock_count": 34, "restock_message": ""},
    {"name": "scented candle set", "in_stock": True, "stock_count": 52, "restock_message": ""},
    {"name": "ceramic vase", "in_stock": False, "stock_count": 0, "restock_message": "Expected back in stock around 2026-05-20."},
    {"name": "bamboo photo frame", "in_stock": True, "stock_count": 15, "restock_message": ""},
    {"name": "marble coaster set", "in_stock": True, "stock_count": 22, "restock_message": ""},
    {"name": "wicker storage basket", "in_stock": False, "stock_count": 0, "restock_message": "Expected back in stock around 2026-06-01."},
    {"name": "velvet cushion cover", "in_stock": True, "stock_count": 67, "restock_message": ""},
    {"name": "terracotta plant pot", "in_stock": True, "stock_count": 44, "restock_message": ""},
    {"name": "hanging wall clock", "in_stock": True, "stock_count": 11, "restock_message": ""},
    # Fashion (6)
    {"name": "linen shirt", "in_stock": True, "stock_count": 30, "restock_message": ""},
    {"name": "leather belt", "in_stock": True, "stock_count": 18, "restock_message": ""},
    {"name": "wool scarf", "in_stock": False, "stock_count": 0, "restock_message": "Out of season — returns in October."},
    {"name": "canvas tote bag", "in_stock": True, "stock_count": 75, "restock_message": ""},
    {"name": "silk hair scrunchie", "in_stock": True, "stock_count": 90, "restock_message": ""},
    {"name": "ankle boots", "in_stock": True, "stock_count": 6, "restock_message": "Low stock — order soon."},
    # Beauty (5)
    {"name": "rose face oil", "in_stock": True, "stock_count": 28, "restock_message": ""},
    {"name": "vitamin c serum", "in_stock": True, "stock_count": 40, "restock_message": ""},
    {"name": "aloe vera gel", "in_stock": True, "stock_count": 55, "restock_message": ""},
    {"name": "bamboo toothbrush set", "in_stock": False, "stock_count": 0, "restock_message": "Expected back in stock around 2026-05-15."},
    {"name": "lavender bath salts", "in_stock": True, "stock_count": 33, "restock_message": ""},
    # Electronics (5)
    {"name": "wireless charger", "in_stock": True, "stock_count": 19, "restock_message": ""},
    {"name": "bluetooth speaker", "in_stock": True, "stock_count": 7, "restock_message": "Low stock."},
    {"name": "usb-c hub", "in_stock": False, "stock_count": 0, "restock_message": "Expected back in stock around 2026-05-25."},
    {"name": "desk lamp", "in_stock": True, "stock_count": 14, "restock_message": ""},
    {"name": "cable organiser kit", "in_stock": True, "stock_count": 60, "restock_message": ""},
    # Food & Drink (5)
    {"name": "portuguese olive oil", "in_stock": True, "stock_count": 100, "restock_message": ""},
    {"name": "artisan honey jar", "in_stock": True, "stock_count": 42, "restock_message": ""},
    {"name": "sea salt flakes", "in_stock": True, "stock_count": 80, "restock_message": ""},
    {"name": "herbal tea collection", "in_stock": False, "stock_count": 0, "restock_message": "Expected back in stock around 2026-05-12."},
    {"name": "almond cookies tin", "in_stock": True, "stock_count": 25, "restock_message": ""},
    # Sports (4)
    {"name": "yoga mat", "in_stock": True, "stock_count": 23, "restock_message": ""},
    {"name": "resistance bands set", "in_stock": True, "stock_count": 50, "restock_message": ""},
    {"name": "water bottle 1l", "in_stock": True, "stock_count": 88, "restock_message": ""},
    {"name": "foam roller", "in_stock": False, "stock_count": 0, "restock_message": "Expected back in stock around 2026-05-18."},
    # Books (3)
    {"name": "portuguese recipes book", "in_stock": True, "stock_count": 16, "restock_message": ""},
    {"name": "mindfulness journal", "in_stock": True, "stock_count": 39, "restock_message": ""},
    {"name": "local travel guide", "in_stock": True, "stock_count": 11, "restock_message": ""},
    # Kids (2)
    {"name": "wooden puzzle set", "in_stock": True, "stock_count": 20, "restock_message": ""},
    {"name": "silicone stacking rings", "in_stock": False, "stock_count": 0, "restock_message": "Expected back in stock around 2026-05-30."},
]
